### ISSUE TITLE
Add Raspberry Pi 3 B+ to compatibility list

### ISSUE THREAD

**Issue by drauschenbach** [d2r2/go-i2c#6]
The README's compatibility list can be expanded with a mention of the Pi 3 B+, which I have been using successfully via [go-bsbmp](https://github.com/d2r2/go-bsbmp) for the past 3 months. I demoed that at RedisConf19, in this [SlideShare](https://www.slideshare.net/DavidRauschenbach/developing-and-deploying-edge-analytics-with-redis) on p19.

**Comment by d2r2** [comment]
Hi @drauschenbach. It's pleasure to know, that my hobby library is used in real projects :) I will update README during a week. Thanks!

**Comment by d2r2** [comment]
Resolved.
