### ISSUE TITLE
i2c Mux

### ISSUE THREAD

**Issue by gesaleh** [d2r2/go-i2c#7]
Hi 

i have been using the i2c on raspberry to access mux then i2c devices
suing i2cset 0x072 0x04 set the i2C to listen to port 1 of mux address 0x72
when i sue go-i2c I sue 
_, err := i2c.Write([]byte{0x72, 0x04, 0x04})
or 
_, err := i2c.Write([]byte{0x72, 0x04})

it is not making the port/channel assignment correctly 
i see always data from same port/address

**Comment by d2r2** [comment]
@gesaleh, I can't help you in situation when I know nothing about equipment you use. Also I don't know what embedded platform you use, OS install at your embedded platform...
In any case, I personally have supported almost a dozen sensors from different manufacturers, and all mentioned sensors works good with I2C library. So try to find what is wrong with you mux equipment.
